### PR TITLE
Add compatibility with DataModel 3.0

### PR DESCRIPTION
**Pull request by Benestar**
This patch adapts the changes made in DataModel 3.0 and makes WikibaseDataModelSerialization ready for that release. @JanZerebecki

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
So this is basically what #115 already does?

**Comment by Benestar** [comment]
Heh, didn't see that -.- also, your patch seems to be a bit older and the tests fail there :S

**Comment by JeroenDeDauw** [comment]
Well yeah, this is one of the things that happen when we just leave such stuff sit there

**Comment by addshore** [comment]
All looks good!
I guess we can close #115 now?

**Pull request merged**
