### PR TITLE
Add support for additional entity serializers and deserializers

### PR DESCRIPTION
**Pull request by Benestar**
This patch adds an optional parameter to the factory constructors that
allows to inject additional serializers and deserializers to handle custom
entity types.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This is not needed. You can simply construct a new `DisplatchingDeserializer` in the "new entity serializer" factory function of your application.

**Comment by Benestar** [comment]
That's true. However, we have to make sure that eg. in Wikibase.git all places that instantiate a `Entity(De)Serializer` know about the additional entity types and not only the places where the factory gets created.

**Comment by JeroenDeDauw** [comment]
Are you saying this factory is getting passed around outside of the main wikibase factory? That's dubious... Though even if that is the case, this is a problem to solve there. Doing it here is shoving dependency injection responsibilities of the wikibase.git apps into a library they use.

**Comment by Benestar** [comment]
Apparently this is relevant: see `Wikibase\Repo\Api\ResultBuilder` which deals with a `SerializerFactory` instance that gets injected.

**Comment by thiemowmde** [comment]
I agree with @JeroenDeDauw that this custom factory stuff should not be here, in this component. This should be done on the application level, where the additional entity types live. It should be possible to wrap the call to `newEntitySerializer` in a `DisplatchingDeserializer` and use that.

**Pull request closed without merging**
