### PR TITLE
Replace Snaks interface with SnakList

### PR DESCRIPTION
**Pull request by thiemowmde**
~~This requires https://github.com/wmde/WikibaseDataModel/pull/467.~~

### CODE REVIEW

**Comment by Benestar** [comment]
Shouldn't we rename the `SnaksSerializer` to `SnakListSerializer` then as the `Snaks` interface is to be removed and the class will only be able to handle `SnakList` objects?

**Comment by JeroenDeDauw** [comment]
That'd be nice yes, not something required for this commit though

**Comment by Benestar** [comment]
Done within #132

**Comment by thiemowmde** [comment]
Not 100%.

**Pull request merged**
