### PR TITLE
Improve documentation of confusing newEntity(De)Serializer methods

### PR DESCRIPTION
**Pull request by thiemowmde**
This should be done before #220.

[Bug: T160436](https://phabricator.wikimedia.org/T160436)

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Sorry, @manicki and I released 2.5.0 without noticing this PR… I’ll rebase it and change the milestone to 2.6.0. (In case the rebase is bad: the current commit hash is d669bc4f6ce66be9d59b011abb77d60bae2db918.)

**Comment by thiemowmde** [comment]
Thanks! Looks good to me. Do you think we can merge this now?

**Comment by lucaswerkmeister** [comment]
That would probably be convenient just for the `RELEASE-NOTES.md` and `composer.json` changes (otherwise other pull requests have to do the same thing). Any objections from @JeroenDeDauw (regarding [this comment](https://github.com/wmde/WikibaseDataModelSerialization/pull/220#pullrequestreview-28730500))?

**Comment by manicki** [comment]
I note this references a Phabricator ticket closed as "invalid" which makes me suspicious :)

**Comment by thiemowmde** [comment]
The ticket got closed because it asked for "removal" of the methods, which was never necessary. The problem was that the methods have been misused. These usages are fixed for a while now.

Right now the methods are unused, dead code. We can deprecate or remove them (as I already tried to do in #220) with pretty much no consequence.

Note that there is a single call to the now deprecated newEntityDeserializer method in Wikibase\InternalSerialization\DeserializerFactory::newEntityDeserializer. But this is also unused, dead code because said DeserializerFactory is never constructed with the third constructor parameter set to null.

Because of this usage a deprecation phase is the most convenient thing to do. Next step will be to remove the nullable feature from DeserializerFactory constructor.

**Comment by JeroenDeDauw** [comment]
I am not enthusiastic about this change but can see how this code can be confusing in some situations due to decisions elsewhere. To me that is just another indication these decisions are dubious.

I'd be a lot more happy with just adding a note to these methods that states they are for the core Wikibase domain, and not other things that are now being added. Now I wrote this I realized it's probably better to specify this in the README as well, since this component only provides services for the core Wikibase domain (and if I'm not mistaken you are not planning on changing that).

As to the code being dead: I suspect I have PHP libs/tools that are using it (and doing so in a way that is not confusing).

**Comment by thiemowmde** [comment]
I removed the `@deprecated` tags and improved the documentation instead.

**Comment by JeroenDeDauw** [comment]
I stated I think this is not a nice change, you do with that feedback what you want.

**Comment by lucaswerkmeister** [comment]
Does that apply to the current version as well, which doesn’t deprecate the methods but only updates their documentation? I thought this was what you suggested in [this comment](https://github.com/wmde/WikibaseDataModelSerialization/pull/222#issuecomment-326368334).

**Pull request merged**
