### PR TITLE
Revert "Drop dependency on Wikibase DataModel Services"

### PR DESCRIPTION
**Pull request by Benestar**
Reverts wmde/WikibaseDataModelSerialization#166

This was a breaking change and should not get released as a 1.9 but a 2.0. We must do a 1.9.1 release which fixes this issue and then release the changes again as 2.0.

### CODE REVIEW

**Comment by addshore** [comment]
Bah, looking at this again yes this is indeed a breaking change
As the namespace has changed things such as the constructor of DeserializerFactory is not expecting a different object..

**Comment by thiemowmde** [comment]
I wonder why we are now so alarmed about a breaking change in https://github.com/wmde/WikibaseDataModelSerialization/compare/1.9.0...master, when https://github.com/wmde/WikibaseDataModelSerialization/compare/1.8.0...1.9.0 did the exact same breaking change, just the other way around. Do we need to release an "unbreaking" 1.8.1 too? And do the same for https://github.com/wmde/WikibaseInternalSerialization/?

**Comment by addshore** [comment]
We probably should, users of this library would shout otherwise.
I know that as I am one of those users, but I was already using 1.9..

**Comment by JeroenDeDauw** [comment]
A difference with the break we avoided now was that the one already made coincided with a major release of WB DM that this component was adapted to.

**Pull request merged**
